server:
  port: 36240
  servlet:
    context-path: /admin

spring:
  application:
    name: murray-mall-admin
  profiles:
    active: dev

mybatis-plus:
  #  configuration:
  mapper-locations: classpath*:mapper/**/*.xml