server:
  port: 36240
  servlet:
    context-path: /admin

spring:
  application:
    name: murray-mall-admin
  profiles:
    active: dev

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath*:mapper/**/*.xml