spring:
  redis:
    database: 1  #Redis数据库索引(默认为0)
    host: 192.168.0.0.1 #Redis服务器地址
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码
    password: 12345
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数(只用负数值表示没有限制)
        max-wait: -1   #连接池最大阻塞等待时间(只用负数值表示没有限制)
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 2    #连接池中的最小空闲连接
    #连接超时时间(毫秒)
    timeout: 0